# Generated by Django 5.2.8 on 2025-11-08 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='player',
            new_name='scorer',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Y', 'Yellow Card'), ('R', 'Red Card'), ('2Y', 'Second Yellow/Red')], max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.match'),
        ),
        migrations.AlterField(
            model_name='card',
            name='minute',
            field=models.IntegerField(help_text='Time the card was given (1-90+).', verbose_name='Time (min)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='minute',
            field=models.IntegerField(help_text='Time of the goal (1-90+).', verbose_name='Time (min)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(help_text='Team that scored the goal.', on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, help_text='Location where the match was played.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='general_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.match'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='referee_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=999, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referee',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
